"""Float to Numeric for financial columns

Revision ID: b0643643ec2d
Revises: be0e0b0bdbb9
Create Date: 2026-04-10 11:35:42.019322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0643643ec2d'
down_revision = 'be0e0b0bdbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
        batch_op.alter_column('avg_buy_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.alter_column('price_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
        batch_op.alter_column('price_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
        batch_op.alter_column('total_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance_usd',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance_usd',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('total_usd',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('price_usd',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.alter_column('price_usd',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('avg_buy_price',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
